### ISSUE TITLE
Use case diagram

### ISSUE THREAD

**Issue by baptistelvr** [baptistelvr/Restaurant_Booking_Project#4]
Make the Use case diagram based on the Class diagram

**Comment by JackieXan** [comment]
![image](https://github.com/user-attachments/assets/535b85da-ecbf-4c52-af19-f530e773bd56)

**Comment by JackieXan** [comment]
here is the V2 of the use case, i deleted the reservation system and completed the diagram for a take away reservation restaurant. I still need to perfect it and maybe edit it in the future.
