### ISSUE TITLE
Sequence diagram

### ISSUE THREAD

**Issue by baptistelvr** [baptistelvr/Restaurant_Booking_Project#5]
Make the sequence diagram based on the Class diagram

**Comment by JackieXan** [comment]
![image](https://github.com/user-attachments/assets/3b492140-2556-44d0-a7ff-c4b9aa0af152)
V1, needs to change

**Comment by JackieXan** [comment]
![image](https://github.com/user-attachments/assets/11482941-77dd-402a-8abb-1e2037fda37d)Here is the final version of the sequence diagram, gonna upload the uxf in Diagrams folder
